//! Argv skeletons for invoking the `openscad` CLI.
//!
//! OpenSCAD source is untrusted, so it is only ever passed as argv entries —
//! never interpolated into a shell command. These builders assemble the
//! argument vector (excluding the binary itself, which the caller prepends).
//!
//! Preview mode adds OpenSCAD's `--preview` option; full rendering explicitly
//! selects the CGAL render path with `--render`. The renderer option stays
//! after the source path so OpenSCAD 2021.01 uses its implicit empty value
//! instead of consuming the source path as an optional renderer value.

use crate::camera::camera;

/// Argv to compile SCAD `source_path` to the STL at `output_path`: `-o
/// <output> [definitions] <source>`. Rendering to STL is triggered by the
/// `.stl` output extension.
pub fn compile_args(
    output_path: &str,
    source_path: &str,
    definition_argv: &[String],
) -> Vec<String> {
    let mut args = vec!["-o".to_string(), output_path.to_string()];
    args.extend_from_slice(definition_argv);
    args.push(source_path.to_string());
    args
}

/// Wrap confined source in a Z-plane projection. The caller validates that
/// `z_mm` is finite before calling; the numeric value is generated by the
/// server rather than interpolated from an untrusted string.
pub fn cross_section_source(source: &str, z_mm: f64) -> String {
    let translation = if z_mm == 0.0 { 0.0 } else { -z_mm };
    format!(
        "projection(cut = true) {{\n  translate([0, 0, {translation}]) {{\n{source}\n  }}\n}}\n"
    )
}

/// Argv to render `source_path` to the PNG at `output_path` from the named
/// `view` at `size`×`size` pixels. Typed definitions precede the source path;
/// `None` is returned when `view` is not a known camera.
///
/// `--autocenter --viewall` frame the model; `--colorscheme=Tomorrow` fixes the
/// palette; `preview` selects the fast OpenCSG preview over a CGAL render.
pub fn render_args(
    output_path: &str,
    source_path: &str,
    view: &str,
    size: u32,
    preview: bool,
    definition_argv: &[String],
) -> Option<Vec<String>> {
    let cam = camera(view)?;
    let mut args = vec![
        "-o".to_string(),
        output_path.to_string(),
        "--camera".to_string(),
        cam.to_string(),
        "--imgsize".to_string(),
        format!("{size},{size}"),
        "--autocenter".to_string(),
        "--viewall".to_string(),
        "--colorscheme=Tomorrow".to_string(),
    ];
    args.extend_from_slice(definition_argv);
    args.push(source_path.to_string());
    if preview {
        args.push("--preview".to_string());
    } else {
        args.push("--render".to_string());
    }
    Some(args)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compile_args_snapshot() {
        assert_eq!(
            compile_args(
                "/tmp/out.stl",
                "/tmp/model.scad",
                &["-D".to_string(), "width=70".to_string()],
            ),
            vec!["-o", "/tmp/out.stl", "-D", "width=70", "/tmp/model.scad"]
        );
    }

    #[test]
    fn cross_section_wraps_the_confined_source_at_the_requested_z_plane() {
        assert_eq!(
            cross_section_source("cube(10);", 2.5),
            "projection(cut = true) {\n  translate([0, 0, -2.5]) {\ncube(10);\n  }\n}\n"
        );
        assert!(cross_section_source("sphere(1);", 0.0).contains("[0, 0, 0]"));
    }

    #[test]
    fn render_args_snapshot_with_preview() {
        assert_eq!(
            render_args(
                "/tmp/out.png",
                "/tmp/model.scad",
                "iso",
                512,
                true,
                &["-D".to_string(), "variant=\"print\"".to_string()],
            ),
            Some(vec![
                "-o".to_string(),
                "/tmp/out.png".to_string(),
                "--camera".to_string(),
                "0,0,0,55,0,25,0".to_string(),
                "--imgsize".to_string(),
                "512,512".to_string(),
                "--autocenter".to_string(),
                "--viewall".to_string(),
                "--colorscheme=Tomorrow".to_string(),
                "-D".to_string(),
                "variant=\"print\"".to_string(),
                "/tmp/model.scad".to_string(),
                "--preview".to_string(),
            ])
        );
    }

    #[test]
    fn render_args_without_preview_selects_full_rendering() {
        let args = render_args("o.png", "m.scad", "top", 256, false, &[]).unwrap();
        assert!(!args.contains(&"--preview".to_string()));
        assert_eq!(args.last().unwrap(), "--render");
        assert_eq!(args[args.len() - 2], "m.scad");
        // The camera for `top` is threaded through.
        assert!(args.contains(&"0,0,0,0,0,0,0".to_string()));
    }

    #[test]
    fn render_args_unknown_view_is_none() {
        assert_eq!(render_args("o.png", "m.scad", "nope", 512, true, &[]), None);
    }
}
